# 服务端口配置
server:
  port: 8888
spring:
  application:
    name: Recipe_BackEnd


  datasource:
    url: jdbc:postgresql://localhost:5433/recipedb
    username: root
    password: "1234"
    driver-class-name: org.postgresql.Driver

  # JPA (Hibernate) 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


recipe:
  file:
    upload-dir: ${user.dir}/uploads/
    upload-url: http://localhost:8888/images/